// accessibility-scanning.page.ts
// Auto-generated by playwright-locator-mapper
// URL: https://stagecraftlabs.com/practice/accessibility-scanning  |  Generated: 2026-07-14

import { Page, Locator } from '@playwright/test';

export class AccessibilityScanningPage {
  readonly page: Page;

  // ── Header ──────────────────────────────────────────────
  readonly homeLink: Locator;
  readonly allLabsLink: Locator;
  readonly darkModeToggleButton: Locator;
  readonly markCompleteButton: Locator;
  readonly playwrightDocsLink: Locator;

  // ── Controls ─────────────────────────────────────────────
  readonly accessibleControlsCheckbox: Locator;
  // Text toggles "Has violations" (broken state) / "Accessible" (accessible state) — no testid exists.
  readonly violationStatusBadge: Locator;

  // ── Settings Form (section aria-labelledby="form-heading") ──
  // #form-region is the exact id the AC-4 scan scopes to via `.include("#form-region")`.
  readonly settingsFormSection: Locator;
  readonly formRegion: Locator;
  readonly nameInput: Locator;
  readonly emailInput: Locator;
  readonly submitFormButton: Locator;
  readonly decorativeImage: Locator;

  constructor(page: Page) {
    this.page = page;

    this.homeLink = page.getByRole('link', { name: 'Stagecraft' });
    this.allLabsLink = page.getByRole('link', { name: '← All labs' });
    this.darkModeToggleButton = page.getByRole('button', { name: 'Toggle dark mode' });
    this.markCompleteButton = page.getByRole('button', { name: 'Mark complete' });
    this.playwrightDocsLink = page.getByRole('link', { name: 'Playwright Docs' });

    this.accessibleControlsCheckbox = page.getByRole('checkbox', { name: 'Show accessible controls' });
    this.violationStatusBadge = page.getByText(/^(Has violations|Accessible)$/);

    this.settingsFormSection = page.locator('section', { has: page.getByRole('heading', { name: 'Settings Form' }) });
    this.formRegion = page.locator('#form-region');
    // Broken state has no <label>, only `placeholder="Your name"` (axe's `label` rule accepts a placeholder as
    // a valid accessible name, so this isn't one of the two real axe violations — see the spec file for those).
    // Accessible state labels it "Your Name" via <label for>. Playwright's accessible-name matching is
    // case-insensitive, so one locator covers both states.
    this.nameInput = this.formRegion.getByRole('textbox', { name: /your name/i });
    this.emailInput = this.formRegion.getByRole('textbox', { name: 'Email' });
    this.submitFormButton = this.formRegion.getByRole('button', { name: 'Submit Form' });
    this.decorativeImage = this.formRegion.locator('img');
  }
}
