// api-request-context.page.ts
// Auto-generated by playwright-locator-mapper
// URL: https://stagecraftlabs.com/practice/api-request-context  |  Generated: 2026-06-12

import { Page, Locator } from '@playwright/test';

export class ApiRequestContextPage {
  // ── Inputs ──────────────────────────────────────────────
  readonly newTaskInput: Locator;

  // ── Buttons ─────────────────────────────────────────────
  readonly addButton: Locator;
  readonly markCompleteButton: Locator;

  // ── Links ───────────────────────────────────────────────
  readonly allLabsLink: Locator;
  readonly playwrightDocsLink: Locator;

  // ── Task list ────────────────────────────────────────────
  readonly taskList: Locator;
  readonly taskItems: Locator;

  constructor(page: Page) {
    // ── Inputs ────────────────────────────────────────────
    this.newTaskInput = page.getByLabel('New task title');

    // ── Buttons ───────────────────────────────────────────
    this.addButton = page.getByRole('button', { name: 'Add' });
    this.markCompleteButton = page.getByRole('button', { name: 'Mark complete' });

    // ── Links ─────────────────────────────────────────────
    this.allLabsLink = page.getByRole('link', { name: '← All labs' });
    this.playwrightDocsLink = page.getByRole('link', { name: 'Playwright Docs' });

    // ── Task list ─────────────────────────────────────────
    this.taskList = page.getByRole('list', { name: 'Task list' });
    // data-testid^="task-" — task-N IDs are dynamically assigned by the server
    this.taskItems = page.locator('[data-testid^="task-"]');
  }
}
