// aria-snapshots.page.ts
// Auto-generated by playwright-locator-mapper
// URL: https://stagecraftlabs.com/practice/aria-snapshots  |  Generated: 2026-07-12

import { Page, Locator } from '@playwright/test';

export class AriaSnapshotsPage {
  // ── Heading & Meta ────────────────────────────────────────────────────
  readonly pageHeading: Locator;
  readonly markCompleteButton: Locator;
  // Global sr-only announcer (role=status) mirrors the visible live region below; kept for
  // completeness even though AC-6 targets the visible one.
  readonly srOnlyStatus: Locator;

  // ── Challenge 1 — Accordion ───────────────────────────────────────────
  readonly accordionSection: Locator;
  // The div directly inside the section, scoped past the h2/paragraph — no id/data-testid exists,
  // so this is the most stable structural anchor for a whole-accordion ARIA snapshot.
  readonly accordionRoot: Locator;

  // ── Challenge 2 — Step wizard ─────────────────────────────────────────
  readonly wizardSection: Locator;
  readonly wizardNav: Locator;
  readonly wizardStepList: Locator;
  // The active step's panel is a <div role="form">, not a real <form> tag — a CSS 'form' selector
  // never matches it, so this must be role-based. It is swapped per step (aria-label changes:
  // "Account step", "Profile step", "Preferences step", "Review step") — always re-query, never
  // cache across a step change.
  readonly wizardForm: Locator;
  readonly backButton: Locator;
  readonly nextButton: Locator;

  // ── Challenge 3 — Live region ─────────────────────────────────────────
  readonly liveRegionSection: Locator;
  // Visible announcer, aria-label="Live announcements" (plain div, no implicit role) — the
  // semantic anchor for AC-6's before/after content-change assertions.
  readonly liveAnnouncement: Locator;

  private readonly page: Page;

  constructor(page: Page) {
    this.page = page;

    // ── Heading & Meta ─────────────────────────────────────────────────
    this.pageHeading = page.getByRole('heading', { name: 'ARIA Snapshots', exact: true, level: 1 });
    this.markCompleteButton = page.getByRole('button', { name: 'Mark complete' });
    this.srOnlyStatus = page.locator('[role="status"][aria-live="polite"]');

    // ── Challenge 1 — Accordion ───────────────────────────────────────────
    this.accordionSection = page.locator('section', { has: page.getByRole('heading', { name: 'Challenge 1 — Accordion', level: 2 }) });
    this.accordionRoot = this.accordionSection.locator('> div');

    // ── Challenge 2 — Step wizard ──────────────────────────────────────────
    this.wizardSection = page.locator('section', { has: page.getByRole('heading', { name: 'Challenge 2 — Step wizard', level: 2 }) });
    this.wizardNav = page.getByRole('navigation', { name: 'Registration wizard steps' });
    this.wizardStepList = this.wizardNav.getByRole('listitem');
    this.wizardForm = this.wizardSection.getByRole('form');
    this.backButton = this.wizardSection.getByRole('button', { name: 'Back', exact: true });
    this.nextButton = this.wizardSection.getByRole('button', { name: 'Next', exact: true });

    // ── Challenge 3 — Live region ─────────────────────────────────────────
    this.liveRegionSection = page.locator('section', { has: page.getByRole('heading', { name: 'Challenge 3 — Live region', level: 2 }) });
    this.liveAnnouncement = page.locator('[aria-label="Live announcements"]');
  }

  // Accordion trigger button, keyed by its exact visible label (also its accessible name).
  accordionButton(label: string): Locator {
    return this.accordionSection.getByRole('button', { name: label, exact: true });
  }

  // Accordion content panel (role="region"), keyed by the same label via aria-labelledby.
  accordionPanel(label: string): Locator {
    return this.accordionSection.getByRole('region', { name: label, exact: true });
  }

  // Wizard step trigger button, 1-based (matches the visible "N. Label" numbering).
  wizardStepButton(label: string): Locator {
    return this.wizardNav.getByRole('button', { name: label, exact: true });
  }
}
