// client-storage-partitioning.page.ts
// Auto-generated by playwright-locator-mapper
// URL: https://stagecraftlabs.com/practice/client-storage-partitioning  |  Generated: 2026-07-16

import { Page, Locator } from '@playwright/test';

export class ClientStoragePartitioningPage {
  // ── Theme preference (localStorage) ─────────────────────────────────────
  readonly themePreferenceValue: Locator;
  readonly toggleThemePreferenceButton: Locator;

  // ── Draft note (sessionStorage) ──────────────────────────────────────────
  readonly draftNoteTextbox: Locator;

  // ── Embedded widget (partitioned cookie) ─────────────────────────────────
  readonly widgetStatus: Locator;
  readonly recheckCookieButton: Locator;

  constructor(page: Page) {
    // ── Theme preference — data-testid; value read from localStorage['labTheme'] ──
    this.themePreferenceValue = page.getByTestId('theme-pref-value');
    this.toggleThemePreferenceButton = page.getByRole('button', { name: 'Toggle theme preference' });

    // ── Draft note — id="draft-note"; value read from sessionStorage['labDraftNote'] ──
    this.draftNoteTextbox = page.getByRole('textbox', { name: 'Draft note' });

    // ── Embedded widget — data-testid; unlocks when cookie "widget_partitioned" is present ──
    this.widgetStatus = page.getByTestId('widget-status');
    this.recheckCookieButton = page.getByRole('button', { name: 'Re-check cookie' });
  }
}
