// clock-timers.page.ts
// Auto-generated by playwright-locator-mapper
// URL: https://stagecraftlabs.com/practice/clock-timers  |  Generated: 2026-07-12

import { Page, Locator } from '@playwright/test';

export class ClockTimersPage {
  private readonly page: Page;

  // ── Challenge 1 — Countdown timer ────────────────────────
  readonly countdownDisplay: Locator;
  readonly countdownStartButton: Locator;
  readonly countdownPauseButton: Locator;
  readonly countdownResetButton: Locator;
  readonly timesUpMessage: Locator;

  // ── Challenge 2 — Session expiry toast ───────────────────
  readonly startSessionButton: Locator;
  readonly expiryToast: Locator;
  readonly expiryCountdown: Locator;

  // ── Challenge 3 — Auto-refresh polling ───────────────────
  readonly refreshCount: Locator;
  readonly lastRefreshAgo: Locator;

  // ── Challenge 4 — Date display ────────────────────────────
  readonly currentDate: Locator;

  constructor(page: Page) {
    this.page = page;

    // ── Challenge 1 — Countdown timer ──────────────────────
    this.countdownDisplay = page.getByTestId('countdown');
    this.countdownStartButton = page
      .getByRole('region', { name: 'Challenge 1 — Countdown timer' })
      .getByRole('button', { name: 'Start', exact: true });
    this.countdownPauseButton = page
      .getByRole('region', { name: 'Challenge 1 — Countdown timer' })
      .getByRole('button', { name: 'Pause', exact: true });
    this.countdownResetButton = page.getByRole('region', { name: 'Challenge 1 — Countdown timer' }).getByRole('button', { name: 'Reset' });
    // Dynamically injected on countdown completion — no data-testid on the lab page. The
    // <p role="alert"> has no accessible name (ARIA "alert" role is name-from-author-only,
    // not name-from-content), and the Challenge 1 guidance paragraph contains this phrase as
    // plain text too, so scope to the region and match the alert role directly.
    this.timesUpMessage = page.getByRole('region', { name: 'Challenge 1 — Countdown timer' }).getByRole('alert');

    // ── Challenge 2 — Session expiry toast ─────────────────
    this.startSessionButton = page.getByTestId('start-session');
    // Dynamically injected (role="alert"), auto-dismisses after expiry
    this.expiryToast = page.getByTestId('expiry-toast');
    this.expiryCountdown = page.getByTestId('expiry-countdown');

    // ── Challenge 3 — Auto-refresh polling ─────────────────
    this.refreshCount = page.getByTestId('refresh-count');
    this.lastRefreshAgo = page.getByTestId('last-refresh-ago');

    // ── Challenge 4 — Date display ──────────────────────────
    this.currentDate = page.getByTestId('current-date');
  }

  // Installs the fake clock, then navigates — the clock must be installed before navigation so
  // the app picks it up on load.
  async installAndGoto() {
    await this.page.clock.install();
    await this.page.goto('/practice/clock-timers');
  }

  // Formats a date exactly the way the lab's date-display component renders it.
  expectedDateText(date: Date): string {
    return date.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' });
  }
}
