// console-runtime-diagnostics.page.ts
// Auto-generated by playwright-locator-mapper
// URL: https://stagecraftlabs.com/practice/console-runtime-diagnostics  |  Generated: 2026-07-16

import { Page, Locator } from '@playwright/test';

export class ConsoleRuntimeDiagnosticsPage {
  // ── Action buttons ─────────────────────────────────────────────────────
  readonly logInfoButton: Locator;
  readonly logWarningButton: Locator;
  readonly logErrorButton: Locator;
  readonly throwUncaughtErrorButton: Locator;
  readonly rejectPromiseButton: Locator;
  readonly fetchMissingResourceButton: Locator;

  // ── Action log (data-testid="action-log"; each triggered action appends a <li>) ──
  readonly actionLog: Locator;
  readonly actionLogEntries: Locator;

  constructor(page: Page) {
    // ── Action buttons ──────────────────────────────────────────────────
    this.logInfoButton = page.getByRole('button', { name: 'Log info' });
    this.logWarningButton = page.getByRole('button', { name: 'Log warning' });
    this.logErrorButton = page.getByRole('button', { name: 'Log error' });
    this.throwUncaughtErrorButton = page.getByRole('button', { name: 'Throw uncaught error' });
    this.rejectPromiseButton = page.getByRole('button', { name: 'Reject a promise' });
    this.fetchMissingResourceButton = page.getByRole('button', { name: 'Fetch a missing resource' });

    // ── Action log ───────────────────────────────────────────────────────
    this.actionLog = page.getByTestId('action-log');
    this.actionLogEntries = page.getByTestId('action-log').locator('li');
  }
}
