// custom-assertions.page.ts
// Auto-generated by playwright-locator-mapper
// URL: https://stagecraftlabs.com/practice/custom-assertions  |  Generated: 2026-07-16

import { Page, Locator } from '@playwright/test';

export class CustomAssertionsPage {
  // ── Order card ────────────────────────────────────────────────────────
  readonly orderHeading: Locator;
  readonly orderPrice: Locator;
  readonly orderStatus: Locator;

  // ── Action buttons ────────────────────────────────────────────────────
  readonly advanceStatusButton: Locator;
  readonly markCompleteButton: Locator;

  // ── Rating (radiogroup) ───────────────────────────────────────────────
  readonly ratingGroup: Locator;
  readonly star1: Locator;
  readonly star2: Locator;
  readonly star3: Locator;
  readonly star4: Locator;
  readonly star5: Locator;
  readonly ratingValue: Locator;

  // ── Links ─────────────────────────────────────────────────────────────
  readonly playwrightDocsLink: Locator;

  constructor(page: Page) {
    // ── Order card ─────────────────────────────────────────────────────
    this.orderHeading = page.getByRole('heading', { name: 'Order #A1042' });
    this.orderPrice = page.getByTestId('order-price');
    this.orderStatus = page.getByTestId('order-status');

    // ── Action buttons ───────────────────────────────────────────────────
    this.advanceStatusButton = page.getByRole('button', { name: 'Advance status' });
    this.markCompleteButton = page.getByRole('button', { name: 'Mark complete' });

    // ── Rating (radiogroup) ──────────────────────────────────────────────
    this.ratingGroup = page.getByRole('radiogroup', { name: 'Order rating' });
    this.star1 = page.getByRole('radio', { name: '1 star' });
    this.star2 = page.getByRole('radio', { name: '2 stars' });
    this.star3 = page.getByRole('radio', { name: '3 stars' });
    this.star4 = page.getByRole('radio', { name: '4 stars' });
    this.star5 = page.getByRole('radio', { name: '5 stars' });
    this.ratingValue = page.getByTestId('rating-value');

    // ── Links ─────────────────────────────────────────────────────────────
    this.playwrightDocsLink = page.getByRole('link', { name: 'Playwright Docs' });
  }
}
