// dom-memory-diagnostics.page.ts
// Auto-generated by playwright-locator-mapper
// URL: https://stagecraftlabs.com/practice/dom-memory-diagnostics  |  Generated: 2026-07-16

import { Page, Locator } from '@playwright/test';

export class DomMemoryDiagnosticsPage {
  // ── Action buttons ─────────────────────────────────────────────────────
  readonly spawnToastsButton: Locator;
  readonly clearLeakedNodesButton: Locator;

  // ── Counters (data-testid; text is "<N> active" / "<N> retained nodes") ──
  readonly activeToastCount: Locator;
  readonly graveyardCount: Locator;

  // ── Graveyard list (data-testid="graveyard-item"; one <li> per retained node) ──
  readonly graveyardList: Locator;
  readonly graveyardItems: Locator;

  constructor(page: Page) {
    // ── Action buttons ──────────────────────────────────────────────────
    this.spawnToastsButton = page.getByRole('button', { name: 'Spawn 50 toasts' });
    this.clearLeakedNodesButton = page.getByRole('button', { name: 'Clear leaked nodes' });

    // ── Counters ────────────────────────────────────────────────────────
    this.activeToastCount = page.getByTestId('active-toast-count');
    this.graveyardCount = page.getByTestId('graveyard-count');

    // ── Graveyard list ──────────────────────────────────────────────────
    this.graveyardList = page.getByRole('list', { name: 'Leaked toast nodes' });
    this.graveyardItems = page.getByTestId('graveyard-item');
  }
}
