// dom-memory-diagnostics.page.ts
// Auto-generated by playwright-locator-mapper
// URL: https://stagecraftlabs.com/practice/dom-memory-diagnostics  |  Generated: 2026-07-16

import { Page, Locator, expect } from '@playwright/test';

export class DomMemoryDiagnosticsPage {
  private readonly page: Page;

  // ── Action buttons ─────────────────────────────────────────────────────
  readonly spawnToastsButton: Locator;
  readonly clearLeakedNodesButton: Locator;

  // ── Counters (data-testid; text is "<N> active" / "<N> retained nodes") ──
  readonly activeToastCount: Locator;
  readonly graveyardCount: Locator;

  // ── Graveyard list (data-testid="graveyard-item"; one <li> per retained node) ──
  readonly graveyardList: Locator;
  readonly graveyardItems: Locator;

  constructor(page: Page) {
    this.page = page;

    // ── Action buttons ──────────────────────────────────────────────────
    this.spawnToastsButton = page.getByRole('button', { name: 'Spawn 50 toasts' });
    this.clearLeakedNodesButton = page.getByRole('button', { name: 'Clear leaked nodes' });

    // ── Counters ────────────────────────────────────────────────────────
    this.activeToastCount = page.getByTestId('active-toast-count');
    this.graveyardCount = page.getByTestId('graveyard-count');

    // ── Graveyard list ──────────────────────────────────────────────────
    this.graveyardList = page.getByRole('list', { name: 'Leaked toast nodes' });
    this.graveyardItems = page.getByTestId('graveyard-item');
  }

  // Spawns the fixed 50-toast batch and waits for every toast to auto-dismiss into the graveyard.
  // Verified live: all 50 dismiss within ~1.6s (independent per-toast timers), so 10s is generous.
  async spawnAndWaitForGraveyard() {
    await this.spawnToastsButton.click();
    await expect.poll(() => this.graveyardItems.count(), { timeout: 10_000 }).toBe(50);
  }

  // Total number of elements currently in the document — a general-purpose DOM-leak probe.
  countAllNodes(): Promise<number> {
    return this.page.evaluate(() => document.querySelectorAll('*').length);
  }
}
