// drag-and-drop.page.ts
// Auto-generated by playwright-locator-mapper
// URL: https://stagecraftlabs.com/practice/drag-and-drop  |  Generated: 2026-07-11

import { Page, Locator } from '@playwright/test';

export type KanbanColumnKey = 'todo' | 'in-progress' | 'done';

export class DragAndDropPage {
  // ── Heading & Meta ────────────────────────────────────────────────────
  readonly pageHeading: Locator;
  readonly markCompleteButton: Locator;

  // ── Challenge 1 — Kanban board ───────────────────────────────────────
  readonly todoColumn: Locator;
  readonly inProgressColumn: Locator;
  readonly doneColumn: Locator;

  // ── Challenge 2 — File drop zone — data-testid backs the dynamically-
  // injected "dropped file" confirmation text; treat as semantic, not fragile ─
  readonly dropZone: Locator;
  readonly droppedFileText: Locator;

  // ── Challenge 3 — Sortable list ──────────────────────────────────────
  readonly sortableList: Locator;
  readonly sortableListItems: Locator;

  private readonly page: Page;

  constructor(page: Page) {
    this.page = page;

    // ── Heading & Meta ─────────────────────────────────────────────────
    this.pageHeading = page.getByRole('heading', { name: 'Drag & Drop', exact: true });
    this.markCompleteButton = page.getByRole('button', { name: 'Mark complete' });

    // ── Challenge 1 — Kanban board — data-column is the stable semantic hook,
    // aria-label duplicates it for the a11y tree ─────────────────────────────
    this.todoColumn = page.locator('[data-column="todo"]');
    this.inProgressColumn = page.locator('[data-column="in-progress"]');
    this.doneColumn = page.locator('[data-column="done"]');

    // ── Challenge 2 — File drop zone — exact:true avoids a substring match
    // against the "Challenge 2 — File drop zone" heading region ─────────────
    this.dropZone = page.getByRole('region', { name: 'File drop zone', exact: true });
    this.droppedFileText = page.getByTestId('dropped-file');

    // ── Challenge 3 — Sortable list ───────────────────────────────────────
    this.sortableList = page.getByRole('list', { name: 'Sortable list' });
    this.sortableListItems = this.sortableList.locator('li');
  }

  // ── Kanban column helpers ────────────────────────────────────────────
  column(key: KanbanColumnKey): Locator {
    return this.page.locator(`[data-column="${key}"]`);
  }

  // Count badge rendered inside each column heading, e.g. "To Do 3"
  columnCountBadge(key: KanbanColumnKey): Locator {
    return this.column(key).locator('h3 span');
  }

  columnCards(key: KanbanColumnKey): Locator {
    return this.column(key).locator('[draggable="true"]');
  }

  // Cards are scoped by exact aria-label so the drag always targets the
  // intended card, never an ambiguous match within/across columns.
  card(name: string): Locator {
    return this.page.locator(`[draggable="true"][aria-label="${name}"]`);
  }

  // ── Sortable list helpers ────────────────────────────────────────────
  sortableItem(name: string): Locator {
    return this.page.getByTestId(`sort-item-${name.toLowerCase()}`);
  }

  // Challenge 3 (sortable list) is implemented with raw event dispatch rather than native HTML5
  // drag, per the page's own guidance ("raw dispatchEvent for sortable lists"). Inserts the source
  // item immediately after the target item — verified empirically against the live lab.
  async manualDragReorder(source: Locator, target: Locator) {
    const dataTransfer = await this.page.evaluateHandle(() => new DataTransfer());
    await source.dispatchEvent('dragstart', { dataTransfer });
    await target.dispatchEvent('dragenter', { dataTransfer });
    await target.dispatchEvent('dragover', { dataTransfer });
    await target.dispatchEvent('drop', { dataTransfer });
    await source.dispatchEvent('dragend', { dataTransfer });
  }
}
