// EmulationInputPage
// Auto-generated by playwright-locator-mapper
// URL: https://stagecraftlabs.com/practice/emulation-input  |  Generated: 2026-06-18

import { Page, Locator } from '@playwright/test';

export class EmulationInputPage {
  // ── Buttons ─────────────────────────────────────────────
  readonly openCommandPaletteButton: Locator;
  readonly hoverTriggerButton: Locator;
  readonly scrollToTopButton: Locator;

  // ── Command Palette ──────────────────────────────────────
  readonly commandPaletteDialog: Locator;
  readonly commandsListbox: Locator;
  readonly selectedCommand: Locator;

  // ── Status / Result ──────────────────────────────────────
  readonly executionResult: Locator;

  // ── Tooltip ──────────────────────────────────────────────
  // #hover-tooltip is the aria-describedby target on the trigger button — semantic anchor, not fragile CSS
  readonly hoverTooltip: Locator;

  // ── Responsive Layout ────────────────────────────────────
  readonly responsiveCard: Locator;
  // Both labels are always in the DOM; CSS shows/hides by viewport — assert visibility not text
  readonly responsiveCardMobileLabel: Locator;
  readonly responsiveCardDesktopLabel: Locator;

  // ── Scroll Container ─────────────────────────────────────
  readonly scrollContainer: Locator;

  constructor(page: Page) {
    // ── Buttons ───────────────────────────────────────────
    this.openCommandPaletteButton = page.getByRole('button', { name: 'Open command palette' });
    this.hoverTriggerButton = page.getByRole('button', { name: 'Hover over me' });
    this.scrollToTopButton = page.getByRole('button', { name: '↑ Scroll to top' });

    // ── Command Palette ───────────────────────────────────
    this.commandPaletteDialog = page.getByRole('dialog', { name: 'Command palette' });
    this.commandsListbox = page.getByRole('listbox', { name: 'Commands' });
    this.selectedCommand = page.getByRole('option', { selected: true });

    // ── Status / Result ───────────────────────────────────
    this.executionResult = page.getByRole('status');

    // ── Tooltip ───────────────────────────────────────────
    this.hoverTooltip = page.locator('#hover-tooltip');

    // ── Responsive Layout ─────────────────────────────────
    this.responsiveCard = page.getByTestId('responsive-card');
    this.responsiveCardMobileLabel = page.getByTestId('responsive-card').getByText('Mobile layout (stacked)');
    this.responsiveCardDesktopLabel = page.getByTestId('responsive-card').getByText('Wide layout (side-by-side)');

    // ── Scroll Container ──────────────────────────────────
    this.scrollContainer = page.getByTestId('scroll-container');
  }
}
