// frames-contexts.page.ts
// Auto-generated by playwright-locator-mapper
// URL: https://stagecraftlabs.com/practice/frames-contexts  |  Generated: 2026-07-12

import { Page, Locator, FrameLocator } from '@playwright/test';

export class FramesContextsPage {
  // ── Heading & Meta ────────────────────────────────────────────────────
  readonly pageHeading: Locator;
  readonly markCompleteButton: Locator;

  // ── Challenge tabs ────────────────────────────────────────────────────
  readonly challenge1Tab: Locator;
  readonly challenge2Tab: Locator;

  // ── Challenge 1 — Counter iframe ─────────────────────────────────────
  // The <iframe> element itself, for title/attribute assertions from the top-level page.
  readonly counterFrameElement: Locator;
  // page.frameLocator scopes every subsequent locator call to content inside the frame — a
  // plain page.locator() never reaches these elements, per AC-1.
  readonly counterFrame: FrameLocator;
  readonly counterValue: Locator;
  readonly incrementButton: Locator;
  readonly decrementButton: Locator;
  readonly resetButton: Locator;
  readonly stepInput: Locator;

  // ── Challenge 2 — Login iframe ───────────────────────────────────────
  readonly loginFrameElement: Locator;
  readonly loginFrame: FrameLocator;
  readonly usernameInput: Locator;
  readonly passwordInput: Locator;
  readonly signInButton: Locator;
  // Dynamically-injected status message (role=status, aria-live=polite) — text after submit is
  // "Signed in as {username}" or "Username required" if the field was left empty.
  readonly loginMessage: Locator;

  constructor(page: Page) {
    // ── Heading & Meta ─────────────────────────────────────────────────
    this.pageHeading = page.getByRole('heading', { name: 'Frames & Contexts', exact: true, level: 1 });
    this.markCompleteButton = page.getByRole('button', { name: 'Mark complete' });

    // ── Challenge tabs ────────────────────────────────────────────────
    this.challenge1Tab = page.getByRole('tab', { name: 'Challenge 1' });
    this.challenge2Tab = page.getByRole('tab', { name: 'Challenge 2' });

    // ── Challenge 1 — Counter iframe ─────────────────────────────────
    this.counterFrameElement = page.locator('iframe[title="Counter frame"]');
    this.counterFrame = page.frameLocator('iframe[title="Counter frame"]');
    this.counterValue = this.counterFrame.getByRole('status', { name: 'Counter value' });
    this.incrementButton = this.counterFrame.getByRole('button', { name: 'Increment' });
    this.decrementButton = this.counterFrame.getByRole('button', { name: 'Decrement' });
    this.resetButton = this.counterFrame.getByRole('button', { name: 'Reset' });
    this.stepInput = this.counterFrame.getByLabel('Step size');

    // ── Challenge 2 — Login iframe ─────────────────────────────────────
    this.loginFrameElement = page.locator('iframe[title="Login frame"]');
    this.loginFrame = page.frameLocator('iframe[title="Login frame"]');
    this.usernameInput = this.loginFrame.getByLabel('Username');
    this.passwordInput = this.loginFrame.getByLabel('Password');
    this.signInButton = this.loginFrame.getByRole('button', { name: 'Sign in' });
    this.loginMessage = this.loginFrame.locator('#msg');
  }
}
