// geolocation-permissions.page.ts
// Auto-generated by playwright-locator-mapper
// URL: https://stagecraftlabs.com/practice/geolocation-permissions  |  Generated: 2026-07-13

import { Page, Locator } from '@playwright/test';

export class GeolocationPermissionsPage {
  readonly page: Page;

  // ── Geolocation — actions ─────────────────────────────────
  // <section aria-labelledby="geo-heading"> — accessible name "Find Nearby Cafés"
  readonly geoRegion: Locator;
  readonly findCafesButton: Locator;

  // ── Geolocation — success state ───────────────────────────
  // data-testid="coords" paragraph renders "Latitude: X · Longitude: Y" once position resolves.
  readonly coordsText: Locator;
  // <ul aria-label="Nearby cafés"> — <li> items appear asynchronously after position resolves.
  readonly cafeList: Locator;
  readonly cafeListItems: Locator;

  // ── Geolocation — denied state ────────────────────────────
  // role="alert" injected when getCurrentPosition() rejects (default-blocked in Playwright).
  readonly geoErrorAlert: Locator;

  // ── Clipboard — actions ───────────────────────────────────
  // <section aria-labelledby="clipboard-heading"> — accessible name "Share Link via Clipboard"
  readonly clipboardRegion: Locator;
  readonly copyShareLinkButton: Locator;
  readonly pasteButton: Locator;

  // ── Clipboard — success state ─────────────────────────────
  // role="status" (aria-live polite) — text differs for copy vs paste, filter by text.
  readonly copySuccessStatus: Locator;
  readonly pasteSuccessStatus: Locator;
  // readonly text input, aria-label "Pasted URL" — populated after a successful clipboard read.
  readonly pastedUrlInput: Locator;

  // ── Clipboard — denied state ──────────────────────────────
  // role="alert" — rendered when clipboard-read hasn't been granted (write can still succeed).
  readonly clipboardErrorAlert: Locator;

  // ── Nav ───────────────────────────────────────────────────
  readonly markCompleteButton: Locator;

  constructor(page: Page) {
    this.page = page;

    // ── Geolocation — actions ────────────────────────────────
    this.geoRegion = page.getByRole('region', { name: 'Find Nearby Cafés' });
    this.findCafesButton = this.geoRegion.getByRole('button', { name: 'Find Cafés Near Me' });

    // ── Geolocation — success state ──────────────────────────
    this.coordsText = page.getByTestId('coords');
    this.cafeList = page.getByRole('list', { name: 'Nearby cafés' });
    this.cafeListItems = this.cafeList.getByRole('listitem');

    // ── Geolocation — denied state ───────────────────────────
    this.geoErrorAlert = this.geoRegion.getByRole('alert');

    // ── Clipboard — actions ───────────────────────────────────
    this.clipboardRegion = page.getByRole('region', { name: 'Share Link via Clipboard' });
    this.copyShareLinkButton = this.clipboardRegion.getByRole('button', { name: 'Copy Share Link' });
    this.pasteButton = this.clipboardRegion.getByRole('button', { name: 'Paste' });

    // ── Clipboard — success state ────────────────────────────
    this.copySuccessStatus = this.clipboardRegion.getByRole('status').filter({ hasText: 'Link copied to clipboard!' });
    this.pasteSuccessStatus = this.clipboardRegion.getByRole('status').filter({ hasText: 'Pasted successfully.' });
    this.pastedUrlInput = page.getByRole('textbox', { name: 'Pasted URL' });

    // ── Clipboard — denied state ─────────────────────────────
    this.clipboardErrorAlert = this.clipboardRegion.getByRole('alert');

    // ── Nav ───────────────────────────────────────────────────
    this.markCompleteButton = page.getByRole('button', { name: 'Mark complete' });
  }
}
