// har-recording.page.ts
// Auto-generated by playwright-locator-mapper
// URL: https://stagecraftlabs.com/practice/har-recording  |  Generated: 2026-07-12

import { Page, Locator } from '@playwright/test';
import path from 'path';

export class HarRecordingPage {
  readonly page: Page;

  // The committed HAR fixture recorded from the live GET /api/products endpoint —
  // see docs/test-plan/har-recording.test-plan.md §3.
  private readonly fixtureHar = path.join(process.cwd(), 'fixtures', 'har', 'har-recording', 'products.har');

  // ── Product catalog ─────────────────────────────────────────
  readonly reloadProductsButton: Locator;
  // span[role="status"][aria-live="polite"] — confirmed by DOM inspection. Scoped to the <span>
  // tag (not just role) because a second, transient role="status" <div> (the loading spinner)
  // briefly coexists during a refetch triggered by Reload — confirmed by instrumenting a click
  // via Chrome DevTools. Can't disambiguate by accessible name instead: role="status" only takes
  // its name from an explicit aria-label per the ARIA spec, and this element has none (its text
  // is live-region *content*, not a name) — confirmed by getByRole('status', { name: ... })
  // matching zero elements even though the text is present and correct.
  readonly statusRegion: Locator;
  // The transient spinner region shown only while a refetch is in flight; has an aria-label,
  // unlike statusRegion, so it can be matched by accessible name.
  readonly loadingIndicator: Locator;
  // div[role="alert"] injected only when the products fetch rejects — confirmed by
  // overriding window.fetch to reject and observing the DOM.
  readonly errorRegion: Locator;
  // article[data-testid^="product-"] — confirmed 10 cards, ids product-1..product-10
  readonly productCards: Locator;

  constructor(page: Page) {
    this.page = page;

    // ── Product catalog ────────────────────────────────────────
    this.reloadProductsButton = page.getByTestId('fetch-products');
    this.statusRegion = page.locator('span[role="status"]');
    this.loadingIndicator = page.getByRole('status', { name: 'Loading products' });
    this.errorRegion = page.getByRole('alert');
    this.productCards = page.locator('article[data-testid^="product-"]');
  }

  /** Returns the product card <article> for a given product name (exact match on the name paragraph). */
  productCard(name: string): Locator {
    return this.productCards.filter({ has: this.page.getByText(name, { exact: true }) });
  }

  /** Returns the "In stock" / "Out of stock" badge within a given product's card. */
  stockBadge(name: string): Locator {
    return this.productCard(name).locator('span');
  }

  // Applies the committed HAR fixture. Default `notFound: 'abort'` means any request not present
  // in the HAR is aborted rather than falling back to the network — proven directly by the AC-2
  // negative test. (An earlier version also set `context.setOffline(true)` to force the point, but
  // that blocks navigation at a lower network layer than route interception in Firefox/WebKit —
  // NS_ERROR_OFFLINE — so it isn't cross-browser safe; abort-on-notFound alone is sufficient.)
  async replayFromHar() {
    await this.page.context().routeFromHAR(this.fixtureHar);
  }
}
