// init-scripts.page.ts
// Auto-generated by playwright-locator-mapper
// URL: https://stagecraftlabs.com/practice/init-scripts  |  Generated: 2026-07-14

import { Page, Locator } from '@playwright/test';

export class InitScriptsPage {
  // ── Heading & Meta ────────────────────────────────────────────────────
  readonly pageHeading: Locator;
  readonly markCompleteButton: Locator;

  // ── Onboarding Modal — dynamically shown unless localStorage.onboarded === 'true' ──
  readonly onboardingModal: Locator;
  readonly onboardingDismissButton: Locator;
  readonly onboardingStatus: Locator;

  // ── Feature Flags — reads window.__FLAGS__.betaFeature on load ──────────
  readonly betaFeatureBanner: Locator;
  readonly betaFeatureEmptyState: Locator;

  // ── Lucky Number — reads Math.random() on mount ──────────────────────────
  readonly luckyNumber: Locator;

  constructor(page: Page) {
    // ── Heading & Meta ─────────────────────────────────────────────────
    this.pageHeading = page.getByRole('heading', { name: 'Init Scripts & Seeding' });
    this.markCompleteButton = page.getByRole('button', { name: 'Mark complete' });

    // ── Onboarding Modal — role="dialog", present only when localStorage.onboarded
    // is not exactly "true"; must be seeded via addInitScript before navigation to suppress ──
    this.onboardingModal = page.getByRole('dialog', { name: 'Welcome to Init Scripts!' });
    this.onboardingDismissButton = this.onboardingModal.getByRole('button', { name: "Got it — Don't show again" });
    this.onboardingStatus = page.getByLabel('Onboarding state');

    // ── Feature Flags — no data-testid; banner only rendered when
    // window.__FLAGS__.betaFeature === true, injected via page.addInitScript pre-navigation ──
    this.betaFeatureBanner = page.getByLabel('Beta feature banner');
    this.betaFeatureEmptyState = page.getByLabel('Beta feature status');

    // ── Lucky Number — data-testid backs the deterministic read after
    // stubbing Math.random via addInitScript ──
    this.luckyNumber = page.getByTestId('lucky-number');
  }
}
