// locator-handlers.page.ts
// Auto-generated by playwright-locator-mapper
// URL: https://stagecraftlabs.com/practice/locator-handlers  |  Generated: 2026-07-14

import { Page, Locator } from '@playwright/test';

export class LocatorHandlersPage {
  readonly page: Page;

  // ── Header ──────────────────────────────────────────────
  readonly homeLink: Locator;
  readonly allLabsLink: Locator;
  readonly darkModeToggleButton: Locator;
  readonly markCompleteButton: Locator;
  readonly playwrightDocsLink: Locator;

  // ── Controls ─────────────────────────────────────────────
  readonly forceOverlaysCheckbox: Locator;

  // ── Checkout Flow (region, heading "Checkout Flow") ───────
  readonly checkoutStepsList: Locator;
  readonly stepIndicator: Locator;
  readonly nextButton: Locator;
  readonly placeOrderButton: Locator;
  readonly orderConfirmedStatus: Locator;
  readonly startOverButton: Locator;

  // ── Overlays — generic (role-scoped, AC-5 dialog vs alertdialog) ──
  // role="dialog": matches both the newsletter promo and the cookie-consent banner.
  readonly anyDialog: Locator;
  // role="alertdialog": matches the session survey.
  readonly anyAlertDialog: Locator;

  // ── Overlays — cookie-consent banner (role="dialog") ──────
  // Appears at the Payment → Confirmation transition when overlays are forced. Registered
  // "before navigating" per the lab's guidance so addLocatorHandler catches it whenever it fires.
  readonly cookieConsentDialog: Locator;
  readonly cookieConsentAcceptButton: Locator;

  // ── Overlays — newsletter promo (role="dialog") ───────────
  // Appears at the Cart → Shipping transition when overlays are forced.
  readonly newsletterDialog: Locator;
  readonly newsletterDismissButton: Locator;

  // ── Overlays — session survey (role="alertdialog") ────────
  // Appears at the Shipping → Payment transition when overlays are forced.
  readonly sessionSurveyDialog: Locator;
  readonly sessionSurveyDismissButton: Locator;

  constructor(page: Page) {
    this.page = page;

    this.homeLink = page.getByRole('link', { name: 'Stagecraft' });
    this.allLabsLink = page.getByRole('link', { name: '← All labs' });
    this.darkModeToggleButton = page.getByRole('button', { name: 'Toggle dark mode' });
    this.markCompleteButton = page.getByRole('button', { name: 'Mark complete' });
    this.playwrightDocsLink = page.getByRole('link', { name: 'Playwright Docs' });

    this.forceOverlaysCheckbox = page.getByRole('checkbox', { name: 'Force overlays every step' });

    this.checkoutStepsList = page.getByRole('list', { name: 'Checkout steps' });
    this.stepIndicator = page.locator('p', { hasText: /^Step \d of \d:/ });
    this.nextButton = page.getByRole('button', { name: 'Next' });
    this.placeOrderButton = page.getByRole('button', { name: 'Place Order' });
    this.orderConfirmedStatus = page.getByRole('status').filter({ hasText: 'Order Confirmed!' });
    this.startOverButton = page.getByRole('button', { name: 'Start over' });

    this.anyDialog = page.getByRole('dialog');
    this.anyAlertDialog = page.getByRole('alertdialog');

    this.cookieConsentDialog = page.getByRole('dialog', { name: 'Cookie Consent' });
    this.cookieConsentAcceptButton = this.cookieConsentDialog.getByRole('button', { name: 'Accept & Close' });

    this.newsletterDialog = page.getByRole('dialog', { name: 'Get 10% off your next order!' });
    this.newsletterDismissButton = this.newsletterDialog.getByRole('button', { name: 'No thanks' });

    this.sessionSurveyDialog = page.getByRole('alertdialog', { name: 'Quick Session Survey' });
    this.sessionSurveyDismissButton = this.sessionSurveyDialog.getByRole('button', { name: 'Skip Survey' });
  }
}
