// media-locale.page.ts
// Auto-generated by playwright-locator-mapper
// URL: https://stagecraftlabs.com/practice/media-locale  |  Generated: 2026-07-13

import { Page, Locator } from '@playwright/test';

export class MediaLocalePage {
  readonly page: Page;

  // ── Header ──────────────────────────────────────────────
  readonly homeLink: Locator;
  readonly allLabsLink: Locator;
  readonly darkModeToggleButton: Locator;
  readonly markCompleteButton: Locator;
  readonly playwrightDocsLink: Locator;

  // ── Colour Scheme (section aria-labelledby="color-scheme-heading") ──
  readonly colorSchemeSection: Locator;
  readonly colorSchemeLabel: Locator;

  // ── Reduced Motion (section aria-labelledby="motion-heading") ────────
  readonly motionSection: Locator;
  readonly motionLabel: Locator;

  // ── Print Media (section aria-labelledby="print-heading") ───────────
  // The print banner is not merely CSS-hidden — it does not exist in the DOM at all until a
  // real `page.emulateMedia({ media: 'print' })` flips window.matchMedia('print').matches and
  // the app's own listener renders it (same matchMedia-driven pattern as colour scheme/motion,
  // not a React state toggle or a plain @media CSS visibility rule).
  readonly printSection: Locator;
  readonly printBanner: Locator;

  // ── Locale & Timezone (section aria-labelledby="locale-heading") ────
  readonly localeSection: Locator;
  readonly localeDate: Locator;
  readonly localeCurrency: Locator;

  constructor(page: Page) {
    this.page = page;

    this.homeLink = page.getByRole('link', { name: 'Stagecraft' });
    this.allLabsLink = page.getByRole('link', { name: '← All labs' });
    this.darkModeToggleButton = page.getByRole('button', { name: 'Toggle dark mode' });
    this.markCompleteButton = page.getByRole('button', { name: 'Mark complete' });
    this.playwrightDocsLink = page.getByRole('link', { name: 'Playwright Docs' });

    this.colorSchemeSection = page.locator('section', { has: page.getByRole('heading', { name: 'Colour Scheme' }) });
    this.colorSchemeLabel = page.getByTestId('color-scheme-label');

    this.motionSection = page.locator('section', { has: page.getByRole('heading', { name: 'Reduced Motion' }) });
    this.motionLabel = page.getByTestId('motion-label');

    this.printSection = page.locator('section', { has: page.getByRole('heading', { name: 'Print Media' }) });
    this.printBanner = page.getByTestId('print-banner');

    this.localeSection = page.locator('section', { has: page.getByRole('heading', { name: 'Locale & Timezone' }) });
    this.localeDate = page.getByTestId('locale-date');
    this.localeCurrency = page.getByTestId('locale-currency');
  }
}
