// scroll-lazy-loading.page.ts
// Auto-generated by playwright-locator-mapper
// URL: https://stagecraftlabs.com/practice/scroll-lazy-loading  |  Generated: 2026-07-12

import { Page, Locator } from '@playwright/test';

export class ScrollLazyLoadingPage {
  // ── Heading & Meta ────────────────────────────────────────────────────
  readonly pageHeading: Locator;
  readonly markCompleteButton: Locator;

  // ── Jump to Item widget ──────────────────────────────────────────────
  readonly jumpInput: Locator;
  readonly jumpButton: Locator;

  // ── Activity feed ─────────────────────────────────────────────────────
  readonly feedList: Locator;
  readonly feedItems: Locator;
  // Sentinel only exists in the DOM while more pages remain (hasMore=true) — it is removed
  // and replaced by endMarker once the last page has been fetched, so re-query, never cache.
  readonly sentinel: Locator;
  // data-testid backs the dynamically-injected "all caught up" confirmation; semantic, not fragile.
  readonly endMarker: Locator;

  private readonly page: Page;

  constructor(page: Page) {
    this.page = page;

    // ── Heading & Meta ─────────────────────────────────────────────────
    this.pageHeading = page.getByRole('heading', { name: 'Scroll & Lazy Loading', exact: true });
    this.markCompleteButton = page.getByRole('button', { name: 'Mark complete' });

    // ── Jump to Item widget ──────────────────────────────────────────────
    this.jumpInput = page.getByRole('spinbutton', { name: 'Jump to item number' });
    this.jumpButton = page.getByRole('button', { name: 'Jump', exact: true });

    // ── Activity feed — data-item-id is the stable per-row hook ──────────
    this.feedList = page.getByRole('list', { name: 'Activity feed' });
    this.feedItems = this.feedList.locator('li[data-item-id]');
    this.sentinel = page.locator('section[aria-labelledby="feed-heading"] > div[aria-hidden="true"]');
    this.endMarker = page.getByTestId('end-marker');
  }

  // Row locator scoped by the item's stable data-item-id (1-based, matches API item.id).
  item(id: number): Locator {
    return this.page.locator(`li[data-item-id="${id}"]`);
  }

  itemTitle(id: number): Locator {
    return this.item(id).locator('p').first();
  }
}
