// scroll-lazy-loading.page.ts
// Auto-generated by playwright-locator-mapper
// URL: https://stagecraftlabs.com/practice/scroll-lazy-loading  |  Generated: 2026-07-12

import { Page, Locator, expect } from '@playwright/test';

export class ScrollLazyLoadingPage {
  // Matches the app's real /api/feed page size.
  private readonly pageSize = 8;

  // ── Heading & Meta ────────────────────────────────────────────────────
  readonly pageHeading: Locator;
  readonly markCompleteButton: Locator;

  // ── Jump to Item widget ──────────────────────────────────────────────
  readonly jumpInput: Locator;
  readonly jumpButton: Locator;

  // ── Activity feed ─────────────────────────────────────────────────────
  readonly feedList: Locator;
  readonly feedItems: Locator;
  // Sentinel only exists in the DOM while more pages remain (hasMore=true) — it is removed
  // and replaced by endMarker once the last page has been fetched, so re-query, never cache.
  readonly sentinel: Locator;
  // data-testid backs the dynamically-injected "all caught up" confirmation; semantic, not fragile.
  readonly endMarker: Locator;

  private readonly page: Page;

  constructor(page: Page) {
    this.page = page;

    // ── Heading & Meta ─────────────────────────────────────────────────
    this.pageHeading = page.getByRole('heading', { name: 'Scroll & Lazy Loading', exact: true });
    this.markCompleteButton = page.getByRole('button', { name: 'Mark complete' });

    // ── Jump to Item widget ──────────────────────────────────────────────
    this.jumpInput = page.getByRole('spinbutton', { name: 'Jump to item number' });
    this.jumpButton = page.getByRole('button', { name: 'Jump', exact: true });

    // ── Activity feed — data-item-id is the stable per-row hook ──────────
    this.feedList = page.getByRole('list', { name: 'Activity feed' });
    this.feedItems = this.feedList.locator('li[data-item-id]');
    this.sentinel = page.locator('section[aria-labelledby="feed-heading"] > div[aria-hidden="true"]');
    this.endMarker = page.getByTestId('end-marker');
  }

  // Row locator scoped by the item's stable data-item-id (1-based, matches API item.id).
  item(id: number): Locator {
    return this.page.locator(`li[data-item-id="${id}"]`);
  }

  itemTitle(id: number): Locator {
    return this.item(id).locator('p').first();
  }

  // The sentinel div is recreated by React on every fetch, which races locator-based actionability
  // checks ("element is not attached to the DOM") and its container (not document.body) is the
  // actual scroll parent, so window.scrollTo is a no-op. Calling the sentinel's native
  // scrollIntoView() in-page sidesteps both issues while still moving it into the viewport for the
  // IntersectionObserver to fire.
  async scrollToBottom() {
    await this.page.evaluate(() => {
      document.querySelector('section[aria-labelledby="feed-heading"] > div[aria-hidden="true"]')?.scrollIntoView();
    });
  }

  // Scrolls to the bottom repeatedly until the end marker appears (all pages fetched) or the safety
  // cap is reached. Each iteration's resulting fetch is awaited via a feed-item count increase
  // (toPass) rather than a fixed timeout.
  async scrollUntilEndMarkerVisible(maxIterations = 10) {
    for (let i = 0; i < maxIterations; i++) {
      if (await this.endMarker.isVisible()) return;
      const before = await this.feedItems.count();
      await this.scrollToBottom();
      await expect(async () => {
        const after = await this.feedItems.count();
        expect(after > before || (await this.endMarker.isVisible())).toBe(true);
      }).toPass({ timeout: 5000 });
    }
  }

  // Builds a stubbed /api/feed response payload matching the app's real API contract.
  feedPage(items: { id: number; title: string; body: string }[], pageNum: number, hasMore: boolean, total: number) {
    return {
      items: items.map((i) => ({ ...i, createdAt: '2026-01-01T00:00:00Z' })),
      page: pageNum,
      pageSize: this.pageSize,
      total,
      hasMore,
    };
  }
}
