// server-sent-events.page.ts
// Auto-generated by playwright-locator-mapper
// URL: https://stagecraftlabs.com/practice/server-sent-events  |  Generated: 2026-07-14

import { Page, Locator } from '@playwright/test';

export class ServerSentEventsPage {
  readonly page: Page;

  // ── Header ──────────────────────────────────────────────
  readonly homeLink: Locator;
  readonly allLabsLink: Locator;
  readonly darkModeToggleButton: Locator;
  readonly markCompleteButton: Locator;
  readonly playwrightDocsLink: Locator;

  // ── Build & Deploy Stream controls ──────────────────────
  readonly startStreamButton: Locator;
  readonly stopStreamButton: Locator;
  // Appears only once the stream finishes (role="status", aria-label="Stream done"); absent
  // while idle or mid-stream — assert on the element itself, not just its text, when checking state.
  readonly streamDoneStatus: Locator;

  // ── Event Log ─────────────────────────────────────────────
  readonly eventLogHeading: Locator;
  // The empty-state paragraph is only present before the first Start Stream click; it is
  // replaced by the list once streaming begins, so the two are mutually exclusive.
  readonly eventLogEmptyMessage: Locator;
  readonly eventLogList: Locator;
  readonly eventLogEntries: Locator;
  readonly infoBadges: Locator;
  readonly warnBadges: Locator;
  readonly errorBadges: Locator;
  readonly systemBadges: Locator;

  constructor(page: Page) {
    this.page = page;

    this.homeLink = page.getByRole('link', { name: 'Stagecraft' });
    this.allLabsLink = page.getByRole('link', { name: '← All labs' });
    this.darkModeToggleButton = page.getByRole('button', { name: 'Toggle dark mode' });
    this.markCompleteButton = page.getByRole('button', { name: 'Mark complete' });
    this.playwrightDocsLink = page.getByRole('link', { name: 'Playwright Docs' });

    this.startStreamButton = page.getByRole('button', { name: 'Start Stream' });
    this.stopStreamButton = page.getByRole('button', { name: 'Stop Stream' });
    this.streamDoneStatus = page.getByRole('status', { name: 'Stream done' });

    this.eventLogHeading = page.getByRole('heading', { name: 'Event Log' });
    this.eventLogEmptyMessage = page.getByText('No events yet — start the stream above.');
    this.eventLogList = page.getByRole('list', { name: 'SSE event log' });
    this.eventLogEntries = this.eventLogList.getByRole('listitem');
    this.infoBadges = page.locator('[aria-label="info badge"]');
    this.warnBadges = page.locator('[aria-label="warn badge"]');
    this.errorBadges = page.locator('[aria-label="error badge"]');
    this.systemBadges = page.locator('[aria-label="system badge"]');
  }

  // Locates a specific log entry by its full accessible name, e.g. "info event: Build started".
  logEntry(type: 'system' | 'info' | 'warn' | 'error', message: string): Locator {
    return this.page.getByRole('listitem', { name: `${type} event: ${message}` });
  }
}
