// service-workers.page.ts
// Auto-generated by playwright-locator-mapper
// URL: https://stagecraftlabs.com/practice/service-workers  |  Generated: 2026-07-12

import { Page, Locator, expect } from '@playwright/test';

export class ServiceWorkersPage {
  readonly page: Page;

  // ── Step 1 — Register the service worker ────────────────────
  readonly registerButton: Locator;
  // p[role="status"][aria-live="polite"] — only status live region on the page; no aria-label,
  // so no accessible-name filter is needed/possible (confirmed by DOM inspection).
  readonly registrationStatus: Locator;

  // ── Step 2 — Fetch items ──────────────────────────────────────
  readonly fetchItemsButton: Locator;
  // ul[aria-label="Fetched items"] — absent from the DOM until the first successful fetch.
  readonly fetchedItemsList: Locator;
  readonly fetchedItems: Locator;
  // div[role="alert"] — injected only when the fetch rejects (e.g. offline + SW blocked).
  readonly errorRegion: Locator;

  constructor(page: Page) {
    this.page = page;

    this.registerButton = page.getByRole('button', { name: 'Register service worker' });
    this.registrationStatus = page.getByRole('status');

    this.fetchItemsButton = page.getByTestId('fetch-items-btn');
    this.fetchedItemsList = page.getByRole('list', { name: 'Fetched items' });
    this.fetchedItems = this.fetchedItemsList.getByRole('listitem');
    this.errorRegion = page.getByRole('alert');
  }

  /** Returns the source badge ("cache" | "network" | "route") for the nth fetched item (0-based). */
  itemSourceBadge(index: number): Locator {
    return this.fetchedItems.nth(index).locator('span');
  }

  async registerServiceWorker() {
    await this.registerButton.click();
    await expect(this.registrationStatus).toHaveText('✓ Service worker registered');
  }
}
