// shadow-dom.page.ts
// Auto-generated by playwright-locator-mapper
// URL: https://stagecraftlabs.com/practice/shadow-dom  |  Generated: 2026-07-14

import { Page, Locator } from '@playwright/test';

export class ShadowDomPage {
  readonly page: Page;

  // ── Header ──────────────────────────────────────────────
  readonly homeLink: Locator;
  readonly allLabsLink: Locator;
  readonly darkModeToggleButton: Locator;
  readonly markCompleteButton: Locator;
  readonly playwrightDocsLink: Locator;

  // ── Star Rating Widget (custom element <rating-widget>, open shadow root) ──
  // Host element carries the `value` attribute reflecting the selected star; it has no
  // ARIA role of its own, so the tag selector is the only way to reach it for evaluate().
  readonly ratingWidgetHost: Locator;
  readonly ratingRadiogroup: Locator;
  readonly starRadios: Locator;
  readonly star1Radio: Locator;
  readonly star2Radio: Locator;
  readonly star3Radio: Locator;
  readonly star4Radio: Locator;
  readonly star5Radio: Locator;

  // ── Labelled Input Widget (custom element <labelled-input>, open shadow root) ──
  readonly nameInput: Locator;
  // The <label>Your name</label> text node lives inside the shadow root itself — used to
  // confirm getByText pierces shadow roots the same way it locates text in regular DOM.
  readonly nameLabelText: Locator;

  // ── Submit Review ────────────────────────────────────────
  readonly submitButton: Locator;
  readonly confirmationStatus: Locator;

  constructor(page: Page) {
    this.page = page;

    this.homeLink = page.getByRole('link', { name: 'Stagecraft' });
    this.allLabsLink = page.getByRole('link', { name: '← All labs' });
    this.darkModeToggleButton = page.getByRole('button', { name: 'Toggle dark mode' });
    this.markCompleteButton = page.getByRole('button', { name: 'Mark complete' });
    this.playwrightDocsLink = page.getByRole('link', { name: 'Playwright Docs' });

    this.ratingWidgetHost = page.locator('rating-widget');
    this.ratingRadiogroup = page.getByRole('radiogroup', { name: 'Star rating' });
    this.starRadios = page.getByRole('radio');
    this.star1Radio = page.getByRole('radio', { name: '1 star' });
    this.star2Radio = page.getByRole('radio', { name: '2 stars' });
    this.star3Radio = page.getByRole('radio', { name: '3 stars' });
    this.star4Radio = page.getByRole('radio', { name: '4 stars' });
    this.star5Radio = page.getByRole('radio', { name: '5 stars' });

    this.nameInput = page.getByLabel('Your name');
    this.nameLabelText = page.getByText('Your name');

    this.submitButton = page.getByRole('button', { name: 'Submit' });
    this.confirmationStatus = page.getByRole('status');
  }
}
