// storage-state.page.ts
// Auto-generated by playwright-locator-mapper
// URL: https://stagecraftlabs.com/practice/storage-state  |  Generated: 2026-07-12

import { Page, Locator, BrowserContext } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

export class StorageStatePage {
  // ── Profile — Authenticated identity ────────────────────
  readonly profileCard: Locator;
  readonly displayName: Locator;
  readonly userRole: Locator;

  // ── Admin-only content ───────────────────────────────────
  readonly adminPanel: Locator;
  readonly totalUsers: Locator;
  readonly pendingReviews: Locator;

  // ── Unauthenticated state ────────────────────────────────
  readonly notAuthenticated: Locator;

  constructor(page: Page) {
    // ── Profile — Authenticated identity ───────────────────
    this.profileCard = page.getByTestId('profile-card');
    this.displayName = page.getByTestId('display-name');
    this.userRole = page.getByTestId('user-role');

    // ── Admin-only content — data-testid, present only when role === 'admin' ──
    this.adminPanel = page.getByTestId('admin-panel');
    this.totalUsers = page.getByTestId('total-users');
    this.pendingReviews = page.getByTestId('pending-reviews');

    // ── Unauthenticated state — shown when no valid session cookie is present ──
    this.notAuthenticated = page.getByTestId('not-authenticated');
  }

  // Logs in via the fake-auth UI login form on the given page and serializes the resulting
  // session to statePath. Static because callers drive freshly-created contexts/pages (setup
  // hooks), not the fixture-bound instance.
  static async loginAndSaveState(page: Page, context: BrowserContext, username: string, password: string, statePath: string) {
    await page.goto('/practice/fake-auth');
    await page.getByRole('textbox', { name: 'Username' }).fill(username);
    await page.getByRole('textbox', { name: 'Password' }).fill(password);
    await page.getByRole('button', { name: 'Sign in' }).click();
    await page.waitForURL(/\/practice\/fake-auth\/dashboard$/);
    fs.mkdirSync(path.dirname(statePath), { recursive: true });
    await context.storageState({ path: statePath });
  }

  // Reads the session cookie ('connect.sid') from a saved storage-state file.
  static readSessionCookie(statePath: string) {
    const state = JSON.parse(fs.readFileSync(statePath, 'utf-8'));
    return state.cookies.find((c: { name: string }) => c.name === 'connect.sid');
  }
}
