// storage-state.page.ts
// Auto-generated by playwright-locator-mapper
// URL: https://stagecraftlabs.com/practice/storage-state  |  Generated: 2026-07-12

import { Page, Locator } from '@playwright/test';

export class StorageStatePage {
  // ── Profile — Authenticated identity ────────────────────
  readonly profileCard: Locator;
  readonly displayName: Locator;
  readonly userRole: Locator;

  // ── Admin-only content ───────────────────────────────────
  readonly adminPanel: Locator;
  readonly totalUsers: Locator;
  readonly pendingReviews: Locator;

  // ── Unauthenticated state ────────────────────────────────
  readonly notAuthenticated: Locator;

  constructor(page: Page) {
    // ── Profile — Authenticated identity ───────────────────
    this.profileCard = page.getByTestId('profile-card');
    this.displayName = page.getByTestId('display-name');
    this.userRole = page.getByTestId('user-role');

    // ── Admin-only content — data-testid, present only when role === 'admin' ──
    this.adminPanel = page.getByTestId('admin-panel');
    this.totalUsers = page.getByTestId('total-users');
    this.pendingReviews = page.getByTestId('pending-reviews');

    // ── Unauthenticated state — shown when no valid session cookie is present ──
    this.notAuthenticated = page.getByTestId('not-authenticated');
  }
}
