// touch-gestures.page.ts
// Auto-generated by playwright-locator-mapper
// URL: https://stagecraftlabs.com/practice/touch-gestures  |  Generated: 2026-07-14

import { Page, Locator } from '@playwright/test';

export class TouchGesturesPage {
  // ── Heading & Meta ────────────────────────────────────────────────────
  readonly pageHeading: Locator;
  readonly markCompleteButton: Locator;

  // ── Tap Counter — data-testid backs the count; only `tap()` (touch)
  // increments it, `click()` (mouse) must leave it unchanged ──────────────
  readonly tapTargetButton: Locator;
  readonly tapCount: Locator;

  // ── Swipe Carousel — role="region" carousel; active slide is a single
  // div whose aria-label/text updates on swipe, not a stack of hidden slides ──
  readonly carouselRegion: Locator;
  readonly activeSlide: Locator;
  readonly slideIndicators: Locator;
  readonly slideIndicatorTap: Locator;
  readonly slideIndicatorSwipe: Locator;
  readonly slideIndicatorPinch: Locator;
  readonly previousSlideButton: Locator;
  readonly nextSlideButton: Locator;

  // ── Device Touch Info — result paragraph only exists after clicking
  // "Inspect Touch Points"; compare across a default vs. devices["iPhone 15"] context ──
  readonly inspectTouchPointsButton: Locator;
  readonly touchInfoResult: Locator;

  constructor(page: Page) {
    // ── Heading & Meta ─────────────────────────────────────────────────
    this.pageHeading = page.getByRole('heading', { name: 'Touch & Mobile Gestures' });
    this.markCompleteButton = page.getByRole('button', { name: 'Mark complete' });

    // ── Tap Counter ──────────────────────────────────────────────────────
    this.tapTargetButton = page.getByRole('button', { name: 'Tap target' });
    this.tapCount = page.getByTestId('tap-count');

    // ── Swipe Carousel — indicator buttons carry aria-current="true" on the
    // active slide; activeSlide locator matches the live-region slide content.
    // exact: true avoids matching the outer "Swipe Carousel" section, whose accessible
    // name also contains the substring "Carousel" ──
    this.carouselRegion = page.getByRole('region', { name: 'Carousel', exact: true });
    this.activeSlide = this.carouselRegion.locator('[aria-live="polite"]');
    this.slideIndicators = page.getByLabel('Slide indicators').getByRole('button');
    this.slideIndicatorTap = page.getByRole('button', { name: 'Go to Slide 1 — Tap' });
    this.slideIndicatorSwipe = page.getByRole('button', { name: 'Go to Slide 2 — Swipe' });
    this.slideIndicatorPinch = page.getByRole('button', { name: 'Go to Slide 3 — Pinch' });
    this.previousSlideButton = page.getByRole('button', { name: 'Previous slide' });
    this.nextSlideButton = page.getByRole('button', { name: 'Next slide' });

    // ── Device Touch Info ────────────────────────────────────────────────
    this.inspectTouchPointsButton = page.getByRole('button', { name: 'Inspect Touch Points' });
    this.touchInfoResult = page.getByLabel('Touch info result');
  }
}
