// visual-regression.page.ts
// Auto-generated by playwright-locator-mapper
// URL: https://stagecraftlabs.com/practice/visual-regression  |  Generated: 2026-07-12

import { Page, Locator } from '@playwright/test';

export class VisualRegressionPage {
  readonly page: Page;

  // ── Button variants (data-testid="button-showcase") ──────────
  readonly buttonShowcase: Locator;
  readonly primaryButton: Locator;
  readonly secondaryButton: Locator;
  readonly dangerButton: Locator;
  readonly ghostButton: Locator;
  readonly disabledButton: Locator;

  // ── Color palette (data-testid="color-palette") ───────────────
  readonly colorPalette: Locator;
  readonly colorSwatches: Locator;

  // ── Metric cards (data-testid="metric-cards") ─────────────────
  // Contains 3 cards, each with its own [data-testid="dynamic-timestamp"] node — masked in
  // screenshot comparisons since the rendered time drifts between runs (AC-4).
  readonly metricCards: Locator;
  readonly dynamicTimestamps: Locator;

  // ── Bar chart (data-testid="bar-chart") ────────────────────────
  readonly barChart: Locator;

  constructor(page: Page) {
    this.page = page;

    this.buttonShowcase = page.getByTestId('button-showcase');
    this.primaryButton = this.buttonShowcase.getByRole('button', { name: 'Primary' });
    this.secondaryButton = this.buttonShowcase.getByRole('button', { name: 'Secondary' });
    this.dangerButton = this.buttonShowcase.getByRole('button', { name: 'Danger' });
    this.ghostButton = this.buttonShowcase.getByRole('button', { name: 'Ghost' });
    this.disabledButton = this.buttonShowcase.getByRole('button', { name: 'Disabled' });

    this.colorPalette = page.getByTestId('color-palette');
    this.colorSwatches = this.colorPalette.getByRole('img');

    this.metricCards = page.getByTestId('metric-cards');
    this.dynamicTimestamps = page.getByTestId('dynamic-timestamp');

    this.barChart = page.getByTestId('bar-chart');
  }

  // Screenshot captures on this lab were flaky on a bare page.goto(): Playwright's own internal
  // stability check (two captures ~100ms apart) intermittently saw a 1-2px layout shift, most
  // likely a late web-font metrics swap. Waiting on document.fonts.ready plus a settle buffer
  // before every toHaveScreenshot call eliminates it.
  async gotoAndStabilize(url: string) {
    await this.page.goto(url, { waitUntil: 'networkidle' });
    // Force the vertical scrollbar's space to always be reserved, so its otherwise-intermittent
    // appear/disappear toggle (right at the content-height/viewport-height boundary) can't nudge
    // flex layouts by a rounding pixel between two back-to-back screenshot captures.
    await this.page.addStyleTag({ content: 'html { overflow-y: scroll !important; }' });
    await this.page.evaluate(() => document.fonts.ready);
    await this.page.waitForTimeout(800);
  }
}
