// websocket-interception.page.ts
// Auto-generated by playwright-locator-mapper
// URL: https://stagecraftlabs.com/practice/websocket-interception  |  Generated: 2026-07-12

import { Page, Locator, WebSocketRoute } from '@playwright/test';

export class WebsocketInterceptionPage {
  private readonly page: Page;

  // The lab's guidance text references ws://localhost:3001/ws, but the deployed site actually
  // opens a socket at this same-origin path — confirmed by instrumenting the WebSocket
  // constructor on the live page before writing this spec.
  readonly wsUrl = 'wss://stagecraftlabs.com/ws';

  // ── WebSocket connection ──────────────────────────────────
  readonly connectButton: Locator;
  readonly disconnectButton: Locator;
  readonly statusIndicator: Locator;
  readonly messageLog: Locator;
  readonly messageInput: Locator;
  readonly sendButton: Locator;

  constructor(page: Page) {
    this.page = page;

    // ── WebSocket connection ─────────────────────────────────
    this.connectButton = page.getByTestId('ws-connect');
    this.disconnectButton = page.getByTestId('ws-disconnect');
    this.statusIndicator = page.getByTestId('ws-status');
    // Live region (aria-live="polite"); individual entries are plain
    // `<div class="text-content">[time] sender: text</div>` rows with no
    // per-row data-testid — scope assertions with .getByText()/.filter() on this locator.
    this.messageLog = page.getByLabel('WebSocket message log');
    this.messageInput = page.getByLabel('Message to send');
    this.sendButton = page.getByTestId('ws-send');
  }

  // Delays resolving the routeWebSocket handler so the client's WebSocket stays in its
  // "connecting" state long enough to assert against — without this, Playwright opens the
  // mocked socket as soon as the handler is installed and "connecting" is too transient to catch.
  async routeAndDelayOpen(onOpen: (ws: WebSocketRoute) => void, delayMs = 300) {
    await this.page.routeWebSocket(this.wsUrl, async (ws) => {
      await new Promise((resolve) => setTimeout(resolve, delayMs));
      onOpen(ws);
    });
  }

  // Challenge 2 — connect to the real server, forward most frames, but rewrite "ticker" frames.
  routeSelectiveForward() {
    return this.page.routeWebSocket(this.wsUrl, (ws) => {
      const server = ws.connectToServer();
      ws.onMessage((message) => server.send(message));
      server.onMessage((message) => {
        const text = message.toString();
        if (text.includes('ticker')) ws.send('ticker (intercepted): rewritten');
        else ws.send(message);
      });
    });
  }

  // Challenge 3 — let the connection succeed but block outgoing frames containing "block".
  routeBlockingFrames() {
    return this.page.routeWebSocket(this.wsUrl, (ws) => {
      const server = ws.connectToServer();
      ws.onMessage((message) => {
        if (!message.toString().includes('block')) server.send(message);
      });
      server.onMessage((message) => ws.send(message));
    });
  }
}
