// websocket-interception.page.ts
// Auto-generated by playwright-locator-mapper
// URL: https://stagecraftlabs.com/practice/websocket-interception  |  Generated: 2026-07-12

import { Page, Locator } from '@playwright/test';

export class WebsocketInterceptionPage {
  // ── WebSocket connection ──────────────────────────────────
  readonly connectButton: Locator;
  readonly disconnectButton: Locator;
  readonly statusIndicator: Locator;
  readonly messageLog: Locator;
  readonly messageInput: Locator;
  readonly sendButton: Locator;

  constructor(page: Page) {
    // ── WebSocket connection ─────────────────────────────────
    this.connectButton = page.getByTestId('ws-connect');
    this.disconnectButton = page.getByTestId('ws-disconnect');
    this.statusIndicator = page.getByTestId('ws-status');
    // Live region (aria-live="polite"); individual entries are plain
    // `<div class="text-content">[time] sender: text</div>` rows with no
    // per-row data-testid — scope assertions with .getByText()/.filter() on this locator.
    this.messageLog = page.getByLabel('WebSocket message log');
    this.messageInput = page.getByLabel('Message to send');
    this.sendButton = page.getByTestId('ws-send');
  }
}
