name: E2E and API tests (Docker)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  tests:
    name: Run tests in consistent Docker env
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write
      statuses: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Playwright image
        run: |
          docker build --build-arg PLAYWRIGHT_VERSION=1.56.1 -t playwright-tests:1.56.1 .

      - name: Run tests inside container
        env:
          ENV: https://bonigarcia.dev/selenium-webdriver-java
        run: |
          mkdir -p playwright-report test-results snapshots
          docker run --rm \
            --ipc=host \
            -e CI=1 \
            -e ENV="${ENV}" \
            -v "$PWD/playwright-report:/work/playwright-report" \
            -v "$PWD/test-results:/work/test-results" \
            -v "$PWD/snapshots:/work/snapshots" \
            playwright-tests:1.56.1

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: warn

      - name: Upload test-results (traces/videos)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          if-no-files-found: warn
